services:
  server:
    build:
      context: .
      dockerfile: deploy/Dockerfile.server
    ports:
      - "8080:8080"
    environment:
      - UNIRATE_API_KEY=${UNIRATE_API_KEY}

  web:
    build:
      context: .
      dockerfile: deploy/Dockerfile.web
    ports:
      - "80:80"
    depends_on:
      - server
